apiVersion: v1
description: A Helm chart for Activiti Cloud Connector
icon: "https://salaboy.files.wordpress.com/2018/01/acitiviti_icon_fullcolor_github_400x400.png"
name: okta-process-connector
version: 7.1.1
appVersion: 7.1.0.M1
